# Generated by Django 2.1.1 on 2019-03-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0005_explanation_wrong_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='anwer_string',
            new_name='answer_string',
        ),
    ]
