# Generated by Django 2.1.1 on 2020-03-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0011_auto_20200308_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcomponent',
            name='component_text',
            field=models.TextField(default='', help_text='Explanation text', max_length=1000),
        ),
    ]
