# Generated by Django 2.1.1 on 2020-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0013_tutorial_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersise',
            name='text',
            field=models.TextField(default='', help_text='Text of the excersise', max_length=1000, null=True),
        ),
    ]
