# Generated by Django 2.1.1 on 2020-03-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagetest',
            old_name='language_test_group',
            new_name='topic',
        ),
    ]
