# Generated by Django 2.1.1 on 2020-03-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0004_auto_20200326_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersise',
            name='explanation_string',
            field=models.CharField(help_text='Enter the explanation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languagetest',
            name='topic',
            field=models.ForeignKey(help_text='Unique test', null=True, on_delete=django.db.models.deletion.CASCADE, to='languageTests.Topic'),
        ),
    ]
