# Generated by Django 2.1.1 on 2020-03-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0005_auto_20200327_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excersise',
            old_name='explanation_string',
            new_name='explanation',
        ),
    ]
