# Generated by Django 2.1.1 on 2020-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0006_auto_20200327_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excersise',
            name='explanation',
            field=models.TextField(help_text='Enter the explanation', max_length=1000, null=True),
        ),
    ]
