# Generated by Django 2.1.1 on 2020-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0007_auto_20200327_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excersise',
            name='explanation',
        ),
        migrations.AddField(
            model_name='answer',
            name='explanation_string',
            field=models.TextField(help_text='Enter the explanation', max_length=1000, null=True),
        ),
    ]
