# Generated by Django 2.1.1 on 2019-03-25 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0003_auto_20190214_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwer_string', models.CharField(help_text='Enter the answer', max_length=100)),
                ('excersise', models.ForeignKey(help_text='Answer of excersise', null=True, on_delete=django.db.models.deletion.SET_NULL, to='languageTests.Excersise')),
            ],
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain_text', models.TextField(default='', help_text='Explanation text for the answer', max_length=1000)),
                ('answer', models.ForeignKey(help_text='Explanation of the answer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='languageTests.Answer')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languageTests.Language')),
            ],
        ),
    ]
