# Generated by Django 2.1.1 on 2019-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0006_auto_20190326_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='possible_answers',
            field=models.CharField(help_text='Enter the possible answers', max_length=100, null=True),
        ),
    ]
