# Generated by Django 2.1.1 on 2019-10-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0008_languagetest_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('w', 'Place words'), ('s', 'Construct sentance')], default='w', help_text='Tests type', max_length=1),
        ),
    ]
