# Generated by Django 2.1.1 on 2020-03-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0010_auto_20200308_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_component',
        ),
        migrations.AddField(
            model_name='tutorialcomponent',
            name='tutorial',
            field=models.ForeignKey(blank=True, help_text='Tutorial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='languageTests.Tutorial'),
        ),
    ]
