# Generated by Django 2.1.1 on 2020-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0012_tutorialcomponent_component_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.CharField(blank=True, choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('e', 'Expert')], default='b', help_text='Tutorial level', max_length=1),
        ),
    ]
