# Generated by Django 2.1.1 on 2020-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0014_auto_20200313_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcomponent',
            name='component_text',
            field=models.TextField(blank=True, default='', help_text='Explanation text', max_length=1000),
        ),
    ]
