# Generated by Django 2.1.1 on 2020-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetest',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
