# Generated by Django 2.1.1 on 2019-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='level',
            field=models.CharField(blank=True, choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('e', 'Expert')], default='b', help_text='Tests level', max_length=1),
        ),
    ]
