# Generated by Django 2.1.1 on 2020-04-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='seddion_key',
            new_name='session_key',
        ),
    ]
