# Generated by Django 2.1.1 on 2019-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excersises',
            name='text',
            field=models.TextField(default='', help_text='Text of the excersise', max_length=1000),
        ),
    ]
