# Generated by Django 2.1.1 on 2019-02-08 08:59

from django.db import migrations
from django.db import models
from languageTests.models import Excersise, Language, LanguageTest

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('languageTests', '0002_excersises_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excersises',
            new_name='Excersise',
        ),
        migrations.RenameModel(
            old_name='LanguageTests',
            new_name='LanguageTest',
        ),
        migrations.RenameField(
            model_name='languagetest',
            old_name='excersises',
            new_name='excersise',
        ),
	
	    migrations.AlterField(
            model_name='languagetest',
            name='excersise',
		    field = models.ManyToManyField(Excersise, help_text='Select excersises for current Test'),
        ),	
		
		
    ]
