# Generated by Django 2.1.1 on 2019-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190203_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
