# Generated by Django 2.1.1 on 2019-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0004_answer_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='wrong_answer',
            field=models.CharField(help_text='Expected wrong answer', max_length=200, null=True),
        ),
    ]
