# Generated by Django 2.1.1 on 2019-02-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190203_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='labguage',
            new_name='language',
        ),
    ]
