# Generated by Django 2.1.1 on 2019-07-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languageTests', '0007_answer_possible_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='answers',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
